version: '3.4'
services:
  server:
    image: 361917574612.dkr.ecr.us-east-1.amazonaws.com/scandi/server
    container_name: scandi_server
    restart: always
    depends_on:
      - frontend
      - backend
    build:
      dockerfile: ./Dockerfile
      context: ./server
    ports:
      - '80:80'
  frontend:
    container_name: scandi_frontend
    image: 361917574612.dkr.ecr.us-east-1.amazonaws.com/scandi/frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile  
    
    
  backend:
    container_name: scandi_backend
    image: 361917574612.dkr.ecr.us-east-1.amazonaws.com/scandi/backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment :
      - DB_URL=mysql://elvis:incorrect@database-1.c0rrseoxusll.us-east-1.rds.amazonaws.com:3306/aaadb
    
    